### ISSUE TITLE
Population growth rate is too high

### ISSUE THREAD

**Issue by Lucas-Armand** [ShiJbey/neighborly#15]
I ran a simulation using Neighborly and noticed that the population growth rate is too high. Even in a small simulation, the population grew from 15 to 70 people in one year. It appears that the duration of pregnancy in the simulation is only one day. This seems unrealistic and I would like to know if there is a way to adjust this setting.

I used the following parameters in my simulation:

```
sim = Neighborly(
    NeighborlyConfig.parse_obj(
        {
            "seed": 8080,
            "relationship_schema": {
                "components": {
                    "Friendship": {
                        "min_value": -100,
                        "max_value": 100,
                    },
                    "Romance": {
                        "min_value": -100,
                        "max_value": 100,
                    },
                    "InteractionScore": {
                        "min_value": -1,
                        "max_value": 1,
                    },
                }
            },
            "plugins": [
                "neighborly.plugins.defaults.names",
                "neighborly.plugins.defaults.characters",
                "neighborly.plugins.defaults.businesses",
                "neighborly.plugins.defaults.residences",
                "neighborly.plugins.defaults.life_events",
                "neighborly.plugins.defaults.ai",
                "neighborly.plugins.defaults.social_rules",
                "neighborly.plugins.defaults.location_bias_rules",
            ]
        }
    )
)

`````
Is there a way to adjust the duration of pregnancy in the simulation to make it more realistic? I would appreciate any help or guidance on this issue.

Thank you!
![image](https://user-images.githubusercontent.com/21991139/229948648-689cc406-913e-4f31-87b9-06e452492573.png)

**Comment by ShiJbey** [comment]
Thanks for using Neighborly!

Pregnancy is supposed to take 9 months of in-simulation time. I thought that I fixed that bug, but I will check and get back to you on that. Currently, there is no way to control the duration of pregnancy from outside the simulation.

**Comment by Lucas-Armand** [comment]
Thank you for making a project so cool!
If you give me same instructions I could try to solve this issues :)

**Comment by ShiJbey** [comment]
This is the line that checks that the current date is before the pregnancy's due date.

https://github.com/ShiJbey/neighborly/blob/8c21789aa75bec143b033fbf68d99055fe585a7d/src/neighborly/systems.py#L358

We set the due date here to be nine months from the day that the child in conceived here:

https://github.com/ShiJbey/neighborly/blob/8c21789aa75bec143b033fbf68d99055fe585a7d/src/neighborly/plugins/defaults/life_events.py#L566

If you want to investigate further, I recommend forking the repository, running some tests, making the necessary changes, and submitting a pull request when you're done. I will merge the pull request into the development branch for the next release.

Thank you so much for your help. I would do it myself, but I'm trying to fix the docs and balance other research tasks 😅.

**Comment by ShiJbey** [comment]
Fixed the pregnancy bug. Closing this issue since version 2 handles residential building and character spawning differently than previous versions.
