### ISSUE TITLE
Change simulation time structure to align with datetime format

### ISSUE THREAD

**Issue by Lucas-Armand** [ShiJbey/neighborly#16]
I noticed that the Neighborly library uses an event-based simulation structure, but the way time is structured in the simulation is problematic. Currently, every month starts on day "00" and every year starts on month "00", which makes it difficult to use event analysis libraries for understanding the simulation (as there is no visualization available yet).

I would like to suggest changing the simulation time structure to align with the datetime format used in libraries such as pandas and numpy. Specifically, I propose that each month start on day 1 and each year start on month 1 (and end on month 12). This would make it easier to use event analysis libraries to gain insights from the simulation.

Thank you for considering this change.
![image](https://user-images.githubusercontent.com/21991139/229950312-7b11a5a0-7dc6-46f3-95b6-53e008543a08.png)
![image](https://user-images.githubusercontent.com/21991139/229950356-b1916c78-4de0-4517-b9bb-0d6d192bad7c.png)

**Comment by ShiJbey** [comment]
Which version of Neighborly are you using? Version 0.10.0 should have the month, day, and year start at 1, and months should roll over to then next after the 28th day.

**Comment by Lucas-Armand** [comment]
![image](https://user-images.githubusercontent.com/21991139/230508420-d68f3907-65b5-470b-bb9c-80cba6b0298d.png)

**Comment by ShiJbey** [comment]
I looked into this, but I have not been able to reproduce this. I ran the CLI and the "simulation_time.py" sample, and both had the correct date formats. I will add a unit test to the next update that will ensure compatibility between Neighborly's date strings and the date string parser for the native datetime module.
