### ISSUE TITLE
neighborly.plugins.defaults.ai not found

### ISSUE THREAD

**Issue by jas-ho** [ShiJbey/neighborly#21]
Stepping through `samples/notebooks/relationship_growth.ipynb` fails with `ModuleNotFoundError: No module named 'neighborly.plugins.defaults.ai'`

I'm on Python 3.10.6 and git commit 48323ae5b4d9f13ff1f405ae2f94ad633fe1def2 (the latest on main as of Jun 27, 2023) and followed the installation instructions for local development.

**Comment by jas-ho** [comment]
(commenting out `"neighborly.plugins.defaults.ai",` on line 26 of the second code cell makes that cell execute without errors; so not a general problem with plugin discovery)

**Comment by ShiJbey** [comment]
Hi @jas-ho. I appreciate your interest in Neighborly. I'm sorry for the error. The `"neighborly.plugins.defaults.ai"` plugin was removed in a previous release, and I forgot to update that sample.

I am currently working on a bunch of simulation updates, bug fixes, and sample updates. I aim to have everything fixed and updated by the end of this weekend.

**Comment by ShiJbey** [comment]
Sample notebook no longer exists
