### ISSUE TITLE
upgrade to esper==3.0 (breaking change)

### ISSUE THREAD

**Issue by gotexis** [ShiJbey/neighborly#26]
seem like in Esper 3.0, the `World` import slightly changed.

**Comment by ShiJbey** [comment]
Thanks for catching this. Esper completely removed their OOP interface in 3.0. Installing esper with `python -m pip install esper==2.*` should fix it. I'll update the `pyproject.toml` file for future installs.

**Comment by ShiJbey** [comment]
Fixed in latest release
